# Generated by Django 2.0 on 2022-01-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=50, verbose_name='content'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
