# Generated by Django 2.0 on 2022-01-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20220130_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='empty', max_length=50, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
